### ISSUE TITLE
Method name for setting a CRS

### ISSUE THREAD

**Issue by benbovy** [benbovy/xproj#3]
Several options:

1. `.proj.set_crs(...)`: like in Xvec and currently implemented
2. `.proj.write_crs(...)`: like in rioxarray
3. `.proj.assign_crs(...)`: like in odc-geo

I have a slight preference for option 3. This is more consistent with methods like Xarray `assign_coords` that also return new Dataset or DataArray objects with new or replaced coordinates.

**Comment by scottyhq** [comment]
> I have a slight preference for option 3. This is more consistent with methods like Xarray assign_coords that also return new Dataset or DataArray objects with new or replaced coordinates. 

I agree! Would be great to align as much as possible with existing Xarray methods and syntax

**Comment by benbovy** [comment]
I also wonder whether we should have a `allow_override=False` option or no option, i.e., in the latter case just leave the responsibility to the user that `assign_crs(spatial_ref=crs)` may overwrite any existing CRS.

odc-geo's `assign_crs()` docstrings says "Assign CRS for a *non-georegistered* array or dataset" but I don't see anything that prevent overwriting an existing CRS in the implementation.
